// modules/app-liferay-cli/sample-react-not-sharing/src/AppComponent.js
import React from 'react';
import ReactDOM from 'react-dom';

export default function AppComponent(props) {
	return (
		<div>
			<div>
				<span className="tag">
					{Liferay.Language.get('portlet-namespace')}:
				</span> 
				<span className="value">{props.portletNamespace}</span>
			</div>
			<div>
				<span className="tag">
					{Liferay.Language.get('context-path')}:
				</span> 
				<span className="value">{props.contextPath}</span>
			</div>
			<div>
				<span className="tag">
					{Liferay.Language.get('portlet-element-id')}:
				</span> 
				<span className="value">{props.portletElementId}</span>
			</div>
			<div>
				<span className="tag">
					{Liferay.Language.get('configuration')}:
				</span> 
				<span className="value pre">{JSON.stringify(props.configuration, null, 2)}</span>
			</div>
		</div>
	);
}

// modules/app-liferay-cli/sample-angular-not-sharing/src/app/app.component.ts
import { Component } from '@angular/core';

import { LiferayParams } from '../types/liferay.params';

declare const Liferay: any;

@Component({
	templateUrl: './app.component.html'
})
export class AppComponent {
	params?: LiferayParams;
	labels: any;

	constructor() {
		this.labels = {        
			
			configuration: Liferay.Language.get('configuration'),
			
			portletNamespace: Liferay.Language.get('portlet-namespace'),
        	contextPath: Liferay.Language.get('context-path'),
			portletElementId: Liferay.Language.get('portlet-element-id'),
		}
	}

	get configurationJSON() {
		return JSON.stringify(this.params?.configuration, null, 2);
	}
}
